### ISSUE TITLE
Idea OpenApi changes - next EAP

### ISSUE THREAD

**Issue by Sorien** [Sorien/silex-idea-plugin#12]
hmm, https://youtrack.jetbrains.com/issue/WI-17116#tab=History (last comment)

**Comment by CarsonF** [comment]
Yeah saw that too, wondering how much that will affect this...

**Comment by Sorien** [comment]
It looks like they will change way how to define type providers and they will create simple/generics providers for array access and non static method ... basically they will introduce way that will be able to replace most functionality of this plugin and plugin will not be needed anymore ... i'll slowdown development till I see what they are planing...

**Comment by CarsonF** [comment]
It may simplify a lot of what you are doing, but I don't think it will make this plugin useless. We have some pretty tight integration with Pimple now (in a good way), I don't think they can make that work out of the box. Plus aren't you also planning for twig and routes support?

**Comment by Sorien** [comment]
they released new EAP, docs https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata

and I don't see anything like 'simpler extension points to plugin authors' in decompiled sources ...

**Comment by CarsonF** [comment]
I don't really like that file format. Are they thinking that file is going to be manually maintained? Probs not! We write generators for that. Then they have to painfully create php output instead of just JSON encoding it.

I still conclude this change doesn't affect or help the plugin at all.

**Comment by Haehnchen** [comment]
i opened an issue: https://youtrack.jetbrains.com/issue/WI-27803. its really useful but not helpful :).

so this is my way of doing it: https://github.com/Haehnchen/idea-php-toolbox/blob/master/tests/de/espend/idea/php/toolbox/utils/test.json

**Comment by Sorien** [comment]
hmm, nice one :)

btw i should thank you for all your hard work on all your plugins, they make idea php plugin developing much more easier ;)
