### ISSUE TITLE
Extend closure with one parameter resolves wrong type

### ISSUE THREAD

**Issue by CarsonF** [Sorien/silex-idea-plugin#13]
``` php
$app->extend('foo', function(Foo $foo) {
    // $foo resolved to Application
});
```

Adding the second parameter to the closure fixes resolving the first parameter correctly

**Comment by Sorien** [comment]
note for me: check what will happen when given $foo type is not typehinted one

**Comment by CarsonF** [comment]
Should note that it doesn't matter whether the first parameter is typehinted or not. It happens in both cases.
