### ISSUE TITLE
Disable Standard CompletionContributor for ArrayAccess autocomplete list

### ISSUE THREAD

**Issue by Sorien** [Sorien/silex-idea-plugin#14]
there are multiple results inside autocomplete list from Silex plugin and from Php plugin ("request" in picture)
![image](https://cloud.githubusercontent.com/assets/1270275/8266682/5e9d1d52-173c-11e5-9209-42342907eb83.png)

i çan't remove duplicates but i can run before Php plugin and stop other completion contributors.

so question is: _do we want to see items from standard Php autocomplete or not?_

as a side effect it will disable new PhpStorm9 ArrayAccess style factory contributor too.

**Comment by CarsonF** [comment]
So basically if a result is found then other "suggestions" won't be listed? Sounds solid...Are there any down sides?

FYI: I'm on vacation this week :)

**Comment by Sorien** [comment]
don't know about any 

> FYI: I'm on vacation this week 

lucky you, have fun!
