### ISSUE TITLE
When you setect item from autocomplete it should replace whole parameter text

### ISSUE THREAD

**Issue by Sorien** [Sorien/silex-idea-plugin#16]
current 

```
$app['re<caret>quest'] (select request_context from list) -> $app['request_contextuest<caret>']
```

should be

```
$app['re<caret>quest'] (select request_context from list) -> $app['request_context<caret>']
```

and ideally move caret after `]`?

**Comment by CarsonF** [comment]
Yeah I think so. That's the default behavior right. I seem to recall some differences between hitting TAB and hitting ENTER. Tab seems to complete it all the way and replace the existing expression, but hitting enter seems to drop in the rest of the completed expression and leaves the existing trailing half there.
