### ISSUE TITLE
Resolve keys for register values

### ISSUE THREAD

**Issue by CarsonF** [Sorien/silex-idea-plugin#19]
``` php
$app->register(new FooSP(), [
    'foo' => 'bar'
//   ^ resolve
]);
```

**Comment by Sorien** [comment]
same for constructor

```
public function __construct(array $values = array()) {
}
```

**Comment by CarsonF** [comment]
Is that for when you are calling the constructor or overriding the constructor? Because with overriding the `$values` doesn't have all the services yet.

**Comment by Sorien** [comment]
i'll leave constructors for future
but i want to know another thing should we show only parameters or services too?

**Comment by CarsonF** [comment]
Hmm interesting...does Pimple actually make the distinction between the two? 
What defines a service, a closure?
I've seen some closures that are basically parameters; they are just inside closures to be lazy.
I'm thinking both.

**Comment by Sorien** [comment]
as there is no way how to find out how they were registered to container plugin is considering simple types and closures as parameters, (objects inherited from \pimple as containers and others as services) ... so maybe parameters are enough

**Comment by CarsonF** [comment]
Ah I am forgetting that the types come from the return value of the closures; it is transparent to the plugin if they are lazy or not. 

Yeah I think parameters would be enough

**Comment by Sorien** [comment]
btw if you have some time after vacation shall i ask you to write some docs for
https://github.com/Sorien/silex-idea-plugin/blob/master/META-INF/plugin.xml#L8 just a few sentences (maybe something how to install it wit SilexProvider) you english is a way better

**Comment by CarsonF** [comment]
Sure I can do that today. Btw I'm always on freenode IRC, it may be easier to chat there

**Comment by Sorien** [comment]
fixed by commit cc9f01118043c8935cece9872a39a39a4bf6a46f

**Comment by CarsonF** [comment]
If that dev version from the link in the readme is up to date with master, then this isn't working yet.

**Comment by Sorien** [comment]
should be up-to-date, its build by tavis during build, its covered by tests so i thought its solved

**Comment by CarsonF** [comment]
Ah it seems the `=>` is needed after the quotes for completion to work. That's a bit unintuitive when one is writing from scratch. But better than nothing :)

**Comment by Sorien** [comment]
Nice find, i'll try to improve it :-)

**Comment by Sorien** [comment]
hope it's fixed now ...
