### ISSUE TITLE
Move pimple.json to .idea folder?

### ISSUE THREAD

**Issue by CarsonF** [Sorien/silex-idea-plugin#20]
Seems like the `.idea` folder would be a better place for this file since it's only for the IDE

**Comment by Sorien** [comment]
.idea folder is hidden in PHPStorm as I remember and i wanted to make it editable by user.

**Comment by CarsonF** [comment]
It is hidden. 

1) Hmmm interesting, never thought about editing it manually I just use the service provider. Also, maybe hidden is a good thing...I don't really want to see it :)

2) Usually people ignore the .idea folder, but since it's not there it would be one more thing to exclude.

Maybe both locations could be checked? Root first, then idea folder.

**Comment by Sorien** [comment]
i want to make it configurable in plugin settings ... i'll think about moving to another location

**Comment by CarsonF** [comment]
Sounds good

**Comment by Sorien** [comment]
#25

**Comment by CarsonF** [comment]
I don't think #25 applies to this. That file suggested could still be in the `.idea` folder.

I still like the idea that both could be supported

**Comment by Sorien** [comment]
yes you are right, its just note for me ... i just want to decide what do do with this with introduction of new format.

**Comment by Sorien** [comment]
comitted
