### ISSUE TITLE
Routes autocomplete

### ISSUE THREAD

**Issue by Sorien** [Sorien/silex-idea-plugin#26]
- [ ] Indexer
- [ ] Dump
- [ ] autocomplete in PHP
- [ ] autocomplete in Twig

**Comment by CarsonF** [comment]
- [ ] Provide completion for `UrlGenerator::generate`
- [ ] Provide completion for `path` and `url` twig methods

**Comment by Haehnchen** [comment]
just install symfony plugin, same syntax :)

**Comment by CarsonF** [comment]
@Haehnchen I forgot about this. But we would still need to add routes from silex syntax to your index/collection/whatever it's called, right?

**Comment by Haehnchen** [comment]
yaml and xml files are supported. you just need to implement the "binds".

``` php
$app->get('/', function () {
    return 'welcome to the homepage';
})
->bind('homepage');
```

If you then attach the php types to `url_generator` you are done. i can add an extension point for routes from external sources just ping me if you need to. i need them too by time.

``` php
$app['url_generator']->generate('homepage')
```

**Comment by CarsonF** [comment]
I'll let @Sorien hit you up when he's ready :)

Do you also provide completion for route parameters?

**Comment by Haehnchen** [comment]
yes, all in :)

**Comment by Sorien** [comment]
not planed
