### ISSUE TITLE
Autocomplete app global in Twig

### ISSUE THREAD

**Issue by CarsonF** [Sorien/silex-idea-plugin#27]
I think this one small thing would go a long ways. Should it be pretty easy to implement, right?

**Comment by CarsonF** [comment]
Was hoping I could persuade you to sneak this in before the rest of the twig stuffs. Given that you plan to do twig work for routes.

**Comment by Sorien** [comment]
there is same problem like routes ... how to detect global vars (indexer/dump/custom annotations) for non global vars its even worth and there are some planed changes in JetBrains twig implementation

**Comment by CarsonF** [comment]
Is it not safe to assume the `app` variable, specifically, is Silex?

It seemed like an edge case in my mind, which didn't have the detection problems.

**Comment by Sorien** [comment]
i would like to reuse s2 plugin and its twig implementation i'll talk to Haehnchen if we can make some extension points to reuse his code ... when it comes to autocompleting app it should be possible but i'd like to wait for ~~https://youtrack.jetbrains.com/issue/WI-27708~~ don't want to make same thing two times

Edit: this issue https://youtrack.jetbrains.com/issue/WI-7093

**Comment by Sorien** [comment]
plugin will support only pimple DI, not enough time to finish whole silex support
