### ISSUE TITLE
Twig Support

### ISSUE THREAD

**Issue by Sorien** [Sorien/silex-idea-plugin#28]
- [ ] Twig Extensions
- [ ] Autocomplete twig files
- [ ] Autocomplete Php types in Twig

and so on

**Comment by Haehnchen** [comment]
Twig Extensions handled by symfony2 plugin.
So all what you need to implement is a "twig namespace delivering". php types and file completion is already inside symfony plugin

**Comment by Sorien** [comment]
not planed
