### ISSUE TITLE
Go To Declaration doesn't work

### ISSUE THREAD

**Issue by CarsonF** [Sorien/silex-idea-plugin#3]
I can't go to declaration of `Foo::bar` method directly from `offsetGet`

``` php
$app['foo']->bar();
```

**Comment by Sorien** [comment]
if you mean this
![image](https://cloud.githubusercontent.com/assets/1270275/8040689/a5b2af5a-0e12-11e5-9598-b1e189355800.png)

as far as i know it can't be done (i've tried it today) there is no extension point for this :/

**Comment by CarsonF** [comment]
Really? Sad day :disappointed:

Is there also no extension point for parameter info?
![screen shot 2015-06-08 at 12 51 44 pm](https://cloud.githubusercontent.com/assets/932566/8041342/2735bc38-0ddd-11e5-9f16-29933244b096.png)

**Comment by Sorien** [comment]
~~yes its same problem because i can't set type to $app[''] directly i have to set type for $app['']->foo() and so function foo don't know it's base class type (no inspection/parameter info/goto and so on)(autocomplete is working only because its a bit hacked to right place)~~

~~if you try `$app['request']->attributes->add();` you will see that you can't CTRL + CLICK to `attributes` but inside `add` it works without problem~~

~~only possible solution is:~~

```
$request = $app['request'];
$request->attributes->add();
```

**Comment by Sorien** [comment]
hmm weird I just tried it again and it's working for me :D .. .please try https://github.com/Sorien/silex-idea-plugin/releases/tag/0.9.3

**Comment by CarsonF** [comment]
Schweeeeet! Updated plugin versions aren't showing on plugins.jetbrains.com or phpstorm, does each version have to be manually sent to them?

**Comment by Sorien** [comment]
yes, i just want somebody to test it before i'll send it

**Comment by CarsonF** [comment]
I can test it if you can walk me through the build process

**Comment by Sorien** [comment]
just download zip archive (silex-plugin.zip) from https://github.com/Sorien/silex-idea-plugin/releases/tag/0.9.3, uninstall old version and install new from disk
![image](https://cloud.githubusercontent.com/assets/1270275/8059722/cacbfb98-0ec1-11e5-9665-91e70058800b.png)

**Comment by CarsonF** [comment]
![screen shot 2015-06-09 at 9 13 06 am](https://cloud.githubusercontent.com/assets/932566/8059865/cdbf38f4-0e87-11e5-8346-2d7073f8786a.png)

Maybe the `plugin.xml` file needs to be updated?

**Comment by Sorien** [comment]
Yes, it seems so. I'll rebuild it when i get home (in 30 mins)

**Comment by Sorien** [comment]
pls try again https://github.com/Sorien/silex-idea-plugin/releases/tag/0.9.4

**Comment by CarsonF** [comment]
This is beautiful! Just beautiful! You've made my month good sir! :+1: :100:
