### ISSUE TITLE
Anonymous function parameter resolved incorrectly

### ISSUE THREAD

**Issue by CarsonF** [Sorien/silex-idea-plugin#34]
`$app` is resolved to `MySqlLock` here instead of `Sliex\Application`

``` php
$app['mutex.lock.mysql'] = function ($app) {
    $db = $app['db'];
    return new MySqlLock($db->getUsername(), $db->getPassword(), $db->getHost());
};
```

This works correctly if wrapped in `$app->share()`

**Comment by Sorien** [comment]
i'll try to look at it during next week, I'm trying to finish house reconstruction and so it's kind of difficult to find some free time for this project :/

**Comment by CarsonF** [comment]
No worries! I assumed you're as busy as I am right now :)

**Comment by CarsonF** [comment]
I'll pull this down and check it out!

**Comment by CarsonF** [comment]
@Sorien I was expecting www.sorien.sk/silex-plugin.zip to be updated. Whoops. Would you mind compiling for me?

**Comment by Sorien** [comment]
it should be updated, I refreshed travis just try to download it again ... 

i'm out of pc just now ... i'll build it tomorrow

**Comment by Sorien** [comment]
i'll close it and release new version in few days if its still present just reopen it, ty
