### ISSUE TITLE
Plugin breaks type inference when accessing objects inside of an array within a foreach loop

### ISSUE THREAD

**Issue by bashofmann** [Sorien/silex-idea-plugin#35]
Example code

```
<?php

class Publication  {

    public function getPublicationDate() {

    }
}

class Event {
    /** @var int */
    public $publicationUid;
}
class MailPublishedFulltextList {

    /**
     * @var Event[]
     */
    public $events = [];

    /** @var Publication[] */
    public $publications;

    public function collect() {
        $this->publications[123]->getPublicationDate();

        foreach ($this->events as $fulltextEvent) {
            $this->publications[$fulltextEvent->publicationUid]->getPublicationDate();
        }
    }
}
```

Expected result:

PhpStorm recognizes that getPublicationDate is a method of Publication.

When the plugin is installed actually PhpStorm $this->publications[$fulltextEvent->publicationUid] references Publication[] instead of Publication.

**Comment by Sorien** [comment]
i'll try to look at it, plugin shouldn't modify autocomplete in any way until $this is not instance of pimple class ... please provide IDEA/PhpStorm Version

**Comment by bashofmann** [comment]
PhpStorm 9.5 EAP 143.129, but the bug is also present in the current stable 9.x releases

**Comment by Sorien** [comment]
@Haehnchen pls maybe you will know where is the problem 
```php
$a = $this->publications[$fulltextEvent->publicationUid]
```
to resolve $a type I'm returning in PimplePhpTypeProvider.getbySignature
phpIndex.getBySignature("#P#C\MailPublishedFulltextList.publications");

but it seems to be internaly resolved to Publication[] and not Publication

**Comment by Sorien** [comment]
@bashofmann could you test it a bit http://silex.sorien.sk/download/master
