### ISSUE TITLE
Array element type inference break

### ISSUE THREAD

**Issue by bburnichon** [Sorien/silex-idea-plugin#36]
Probably linked to #35. But easier to reproduce. I thought it was a phpstorm issue first.

https://youtrack.jetbrains.com/issue/WI-31170

``` php
/** @var int[] $array */
$array = [1, 2, 3];
$index = 0;

$myInt = $array[0];
$myOtherInt = $array[$index];

var_dump($myInt, $myOtherInt);
```

![myint](https://cloud.githubusercontent.com/assets/2437286/13981875/0ec76bae-f0e7-11e5-8195-9cd3dc05586c.png)
![myotherint](https://cloud.githubusercontent.com/assets/2437286/13981876/0ec84f2e-f0e7-11e5-8068-3b2e2eb29e0b.png)

**Comment by Sorien** [comment]
i'll try to look at it and publish new version that should contain fix for #35 as well

**Comment by bburnichon** [comment]
Another issue is the way typehints are interpreted in defining closures:

``` php
class MyContainer extends Pimple
{
}

class MyServiceProvider
{
    public function register(Pimple $container)
    {
        $container['foo'] = 'foo value';
        $container['bar'] = function (MyContainer $container) {
            return $container['foo'];
        };
        $container['baz'] = $container::share(function (MyContainer $container) {
            return $container['foo'];
        });
    }
}

$provider = new MyServiceProvider();
$container = new MyContainer();

$provider->register($container);
```

Type is not inferred for factories:
![image](https://cloud.githubusercontent.com/assets/2437286/14013623/c623655c-f1ad-11e5-81b1-1878a37f10e7.png)

Type is inferred to type calling `Pimple::share()` instead of defined in closure
![image](https://cloud.githubusercontent.com/assets/2437286/14013664/f8cd4888-f1ad-11e5-994c-325ca415f5b1.png)

**Comment by Sorien** [comment]
pls could you try to install plugin based on master http://silex.sorien.sk/download/master and recheck 

i've just found out that i need to setup whole build env :/

**Comment by bburnichon** [comment]
@Sorien I retested on the initial issue. There are no changes (`$myOtherInt` has no type hint). For the Silex Service Providers, both case are now type hinted as `Pimple` even though I explicitly type hinted as `MyContainer`

**Comment by Sorien** [comment]
@Haehnchen pls is there any way how PhpTypeProvider2.getBySignature can return simple (int) php element 

when i call

``` java
        Collection<? extends PhpNamedElement> collection = phpIndex.getBySignature('#C\int', null, 0);
        return collection; 
```

it returns empty collection ... (it's causing bug in first example)

**Comment by Haehnchen** [comment]
you can add string values. hopefully this should also work with primitives types; just try to use `int[]`. doing same with class returns `Foo[]`

``` code
fr.adrienbrault.idea.symfony2plugin.doctrine.ObjectRepositoryResultTypeProvider#getBySignature
        String name = method.getName();
        if(name.equals("findAll") || name.equals("findBy")) {
            method.getType().add(phpClass.getFQN() + "[]");
            return phpNamedElementCollections;
        }
```

**Comment by Sorien** [comment]
@bburnichon first issue should be hopefully fixed at master (with tests) if you want to test it just download from http://silex.sorien.sk/download/master (this plugin build is autogenerated by Travis after each commit)

**Comment by bburnichon** [comment]
@Sorien I confirm that first issue is resolved.

**Comment by Sorien** [comment]
@bburnichon second issue should be fixed with last commit as well

**Comment by bburnichon** [comment]
@Sorien checked second issue is also fixed.

I checked #34 & #35 on my setup. Both issues are solved.

Great work!

**Comment by Sorien** [comment]
ok i'll wait few days in no other bugs are found i'll release new version
