### ISSUE TITLE
False warnings in Phpstorm

### ISSUE THREAD

**Issue by mishavantol** [Sorien/silex-idea-plugin#43]
The plugins seems to trigger false warnings in Phpstorm.

@see https://youtrack.jetbrains.com/issue/WI-36559

**Comment by Sorien** [comment]
as i remember i stopped developing after API breakage in PHPStorm 2016.2 that I could not solve so its not compatible with newer versions, I'm gonna remove it from plugin repo when i find some time...

**Comment by Sorien** [comment]
sorry for inconvenience

**Comment by mishavantol** [comment]
No biggie. 😄
