### ISSUE TITLE
Resolve constants for pimple keys

### ISSUE THREAD

**Issue by CarsonF** [Sorien/silex-idea-plugin#9]
Can constants also be resolved?

``` php
$foo = $app[Service::KEY];
$bar = $app[Service::class]; // For PHP 5.5
```

**Comment by Sorien** [comment]
it should be ... i'll try it

**Comment by Sorien** [comment]
https://github.com/Sorien/silex-idea-plugin/commit/1cef298772d8ab5037b07dd8e69f04188168bad6 
solves all above and one more 

```
class Test {
    public $s = "dispatcher";
}

$c = new Test();
$a = $app[$c->s];
```

**Comment by CarsonF** [comment]
Can this be tagged in the meantime?

**Comment by Sorien** [comment]
i don't want to release new version with every commit ... build special for you [0.9.7.1](http://www.sorien.sk/silex-plugin-0.9.7.1.zip)

**Comment by CarsonF** [comment]
Thank you!
